### ISSUE TITLE
Port for OTRS5

### ISSUE THREAD

**Issue by atavius** [complemento/otrs.SmsEvent#2]
Hi,
I really like your SMS Event for OTRS. Is there any chance of porting for 5.X framework of OTRS?

**Comment by richieri** [comment]
Yes! We are accepting donations if you want to help us porting this code to
5.0 :)

What do you thing?

Ronaldo Richieri
Vivo (11) 97097-7737
TIm  (11) 96424-0676
Oi    (15) 98818-2009
http://richieri.com
skype: rrichieri
twitter: @richieri

2016-08-24 8:26 GMT-03:00 atavius notifications@github.com:

**Comment by atavius** [comment]
Thanks for quick response. What sort of donation are we talking about? :)

**Comment by richieri** [comment]
Or development skills, or money.

Or you can migrate the addon and pull it to our new version, or you can
donate or contract hours of development so we can make the work for you.
Let's say, something like US$ 350,00

Ronaldo Richieri
Vivo (11) 97097-7737
TIm  (11) 96424-0676
Oi    (15) 98818-2009
http://richieri.com
skype: rrichieri
twitter: @richieri

2016-08-24 11:33 GMT-03:00 atavius notifications@github.com:

> Thanks for quick response. What sort of donation are we talking about? :)
>
