### ISSUE TITLE
Custom Gateway

### ISSUE THREAD

**Issue by tobby** [complemento/otrs.SmsEvent#3]
How can one add a custom gateway on this module?

**Comment by richieri** [comment]
Hi!

You need first to create a file under Kernel/Config/Files similar to this:
https://github.com/complemento/otrs.SmsEvent/blob/master/Kernel/Config/Files/SmsEvent-Clickatell.xml

You need of course check your gateway parameters.

Then you need to create control file, like this for example:
https://github.com/complemento/otrs.SmsEvent/blob/master/Kernel/System/Sms/Gateways/Clickatell.pm

If you want to use git, I think that you can clone this repository,  create your files, then you should add it to repository with "git add". After that, you can use git commit and git push to send it to github again :)

Thanks!
